# Generated by Django 4.2.1 on 2023-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=32)),
                ('longitude', models.FloatField(max_length=32)),
                ('location_name', models.FloatField(max_length=32)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
    ]
