# Generated by Django 4.2.1 on 2023-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('social_medias', models.URLField(max_length=32)),
            ],
        ),
    ]
