# Generated by Django 3.2.12 on 2023-07-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_name_customer_first_name'),
        ('basket', '0001_initial'),
        ('shipment', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.basket'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipment',
            field=models.ManyToManyField(blank=True, null=True, to='shipment.Shipment'),
        ),
    ]
